import Vue from 'vue';
import { Button ,Col, Row,  Icon, Swipe, SwipeItem,Image as VanImage, Tabbar, TabbarItem, Grid, GridItem, List, Tab, Tabs, Search, Card, Overlay, Cell, CellGroup, Divider, NavBar, Form, Field, Radio, RadioGroup, Rate, Uploader, Collapse, CollapseItem, Toast, Lazyload, Popup, NoticeBar,  DropdownMenu, DropdownItem, Tag, CountDown, PullRefresh } from 'vant';

Vue.use(Col).use(Row).use(Icon).use(Button).use(Swipe).use(SwipeItem).use(VanImage).use(Tabbar).use(TabbarItem);
//单元格
Vue.use(Grid).use(GridItem)
//列表
Vue.use(List)
//tasklist中的标签页
Vue.use(Tab).use(Tabs)
//搜索栏
Vue.use(Search)
//任务卡片
Vue.use(Card)
//遮罩层
Vue.use(Overlay)
//单元格
Vue.use(Cell).use(CellGroup)
//分割线
Vue.use(Divider)
//引导栏
Vue.use(NavBar)/
//表单
Vue.use(Field).use(Form)
//单选框
Vue.use(Radio).use(RadioGroup)
//评分
Vue.use(Rate)
//附件上传
Vue.use(Uploader)
//折叠面板
Vue.use(Collapse).use(CollapseItem)
//轻提示
Vue.use(Toast)
//懒加载
Vue.use(Lazyload)
//弹出层
Vue.use(Popup)
//通知栏
Vue.use(NoticeBar )
//下拉
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
//标签
Vue.use(Tag)
//倒计时
Vue.use(CountDown);
//下拉刷新
Vue.use(PullRefresh);